GET http://localhost:8080/account/{{accountId}}/balance
Accept: application/json

###
POST http://localhost:8080/account/{{acountId}}/deposit
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "paymentType": "PAYPAL",
  "amount": 100,
  "account": "123456789"
}
