GET http://localhost:3000/resource
###

GET http://localhost:3000/resource/byQuery?value=someThing
###
### working
GET http://localhost:3000/resource/123
###
### not working
GET http://localhost:3000/resource/a123
###

GET http://localhost:3000/resource/throw/error
###

GET http://localhost:3000/resource/redirect/to/resource
###
### working post
POST http://localhost:3000/resource
Content-Type: application/json;charset=UTF-8

{
  "id": 23,
  "name": "resourceName",
  "version": 2.0000
}
###
### not working post
POST http://localhost:3000/resource
Content-Type: application/json;charset=UTF-8

{
  "id": 23,
  "name": "resourceName",
  "version": "2.0000"
}
###
### working put
PUT http://localhost:3000/resource/123
Content-Type: application/json;charset=UTF-8

{
  "id": 23,
  "name": "resourceName",
  "version": 2.00
}
###
### not working put
PUT http://localhost:3000/resource/123
Content-Type: application/json;charset=UTF-8

{
  "id": -23,
  "name": "resourceName",
  "version": -2.00
}
###
### not working put
PUT http://localhost:3000/resource/123
Content-Type: application/json;charset=UTF-8

{
  "id": 23,
  "name": "",
  "version": 2.00
}
###
### working
DELETE http://localhost:3000/resource/123
###
### not working
DELETE http://localhost:3000/resource/a123
###

