### Create User
POST http://localhost:3000/v1/users
Content-Type: application/json

{
  "birthday": "2000-01-01",
  "email": "peter.griffin@test.com",
  "name": "Peter Griffin",
  "password": "Test123!?"
}

> {%
  client.global.set("uuid", response.body.uuid);
%}

### Update User
PUT http://localhost:3000/v1/users
Content-Type: application/json

{
  "uuid": "{{uuid}}",
  "birthday": "2001-01-01",
  "email": "peter.griffin@test.com",
  "name": "Peter GGGriffin",
  "password": "Test123!?"
}

### Get User
GET http://localhost:3000/v1/users/{{uuid}}

### Delete User
DELETE http://localhost:3000/v1/users/{{uuid}}
