GET http://localhost:3000/resource?password=someThing
###

GET http://localhost:3000/resource/123
###

POST http://localhost:3000/resource
Content-Type: application/json;charset=UTF-8

{
  "id": 23,
  "name": "resourceName",
  "password": "TestPa$$word+12"
}
###

POST http://localhost:3000/resource
Content-Type: application/json;charset=UTF-8

{
  "resource": {
    "id": 23,
    "name": "resourceName",
    "password": "TestPa$$word+12"
  }
}
###

